# Задание №1

## Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

# Задание №2

## Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [4]:
a.reshape(2,6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [5]:
a.reshape(3,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [31]:
a.reshape(6, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [29]:
a.reshape(12, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

# Задание №3

## Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [11]:
a.reshape(12, -1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [12]:
a.reshape(6, -1)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [13]:
a.reshape(4, -1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [14]:
a.reshape(-1, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [26]:
a.reshape(-1, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

# Задание №4

## Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


In [33]:
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [37]:
a.shape

(12,)

In [38]:
a.ndim

1

In [44]:
a.reshape(12, 1).shape

(12, 1)

In [45]:
a.reshape(12, 1).ndim

2

In [46]:
## Ответ: массив из одного столбца и 12 строк НЕЛЬЗЯ назвать одномерным, потому что он все равно будет иметь размерность, равную двум.

# Задание №5

## Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [49]:
x = np.random.randn(3, 4)
x

array([[ 0.24745054,  1.75881737,  0.50168852, -1.18233297],
       [-0.040833  ,  0.54039156,  0.59478422,  2.16120479],
       [-0.35990106,  1.34760285,  0.69532206, -0.21205327]])

In [50]:
x.size

12

In [58]:
x = x.flatten()
x

array([ 0.24745054,  1.75881737,  0.50168852, -1.18233297, -0.040833  ,
        0.54039156,  0.59478422,  2.16120479, -0.35990106,  1.34760285,
        0.69532206, -0.21205327])

In [59]:
x.ndim

1

In [60]:
x.size

12

# Задание №6

## Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.


In [62]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

# Задание №7

## Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [72]:
b = np.arange(20, 0, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [69]:
a.ndim

1

In [70]:
b.ndim

2

In [74]:
b.shape

(1, 10)

In [75]:
a.shape

(10,)

In [76]:
## Ответ: а - это одномерный массив, b - двумерный

# Задание №8

## Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [196]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [197]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [198]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [199]:
v.size

10

# Задание №9

## Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [217]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [228]:
a = a.reshape(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [229]:
at = a.T
at

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [230]:
b = np.dot(a, at)
b

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [235]:
b.shape

(4, 4)

In [236]:
np.linalg.det(b)

0.0

In [237]:
np.linalg.inv(b)

LinAlgError: Singular matrix

In [238]:
# Ответ матрица b имеет размер (4, 4) и определитель, равный 0.0, поэтому нельзя вычислить обратную матрицу

# Задание №10

## Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [244]:
np.random.seed(42)

# Задание №11

## Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 


In [266]:
c = np.random.randint(0, 16, 16)
c

array([12, 14, 10, 12,  3, 12, 15,  6, 10,  2,  5, 11,  1,  9, 12, 13])

# Задание №12

## Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [270]:
c = c.reshape(4, 4)
c

array([[12, 14, 10, 12],
       [ 3, 12, 15,  6],
       [10,  2,  5, 11],
       [ 1,  9, 12, 13]])

In [274]:
d = c * 10 + b
d

array([[125, 154, 123, 152],
       [ 44, 170, 236, 182],
       [123, 106, 199, 322],
       [ 42, 212, 332, 432]])

In [275]:
# Определитель матрицы d
np.linalg.det(d)

374596600.00000095

In [276]:
# Ранг матрицы d
np.linalg.matrix_rank(d)

4

In [278]:
# Обратная матрица d
d_inv = np.linalg.inv(d)
d_inv

array([[ 0.00125735,  0.00406699,  0.00822762, -0.00828844],
       [ 0.0116355 , -0.00681432, -0.01203166,  0.00774492],
       [-0.01011018,  0.01500921,  0.00784716, -0.00861508],
       [ 0.0019376 , -0.0085862 , -0.00092617,  0.00594074]])

# Задание №13

## Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [287]:
d_inv = np.where(d_inv < 0, 0, 1)
d_inv

array([[1, 1, 1, 0],
       [1, 0, 0, 1],
       [0, 1, 1, 0],
       [1, 0, 0, 1]])

In [289]:
e = np.where(d_inv == 1, b, c )
e

array([[  5,  14,  23,  12],
       [ 14,  12,  15, 122],
       [ 10,  86, 149,  11],
       [ 32,   9,  12, 302]])